   <nav class="navbar navbar-expand-lg">
       <div class="container">

           <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
               <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
               <ul class="navbar-nav align-items-start">
                   <a class="navbar-brand fw-bold"><a href="home.html">
                           <img src="images/favicon.ico" alts="Logo">
                       </a>
                       <li class="nav-item"><a class="nav-link"><a href="home.html">Home</a></li>
                       <li class="nav-item"><a class="nav-link"><a href="skills.html">All Skills</a></li>
                       <li class="nav-item"><a class="nav-link"><a href="gallery.html">Gallery</a></li>
                       <li class="nav-item"><a class="nav-link"><a href="add.html">Add Skill</a></li>
               </ul>
               <form class="d-flex" role="search">
                   <div class="input-group input-group-sm">
                       <span class="input-group-text bg-white border-end-0"><i class="fas fa-search"></i></span>
                       <input class="form-control border-start-0" type="search" placeholder="Search skills..."
                           aria-label="Search">
                   </div>
               </form>
           </div>
       </div>
   </nav>